import { RepoRecommendation } from './types';
export { BASE_QUICK_ACTIONS } from './quickActionsData';

export function generateRepoRecommendations(repoFullName: string): RepoRecommendation[] {
  return [
    {
      id: 'rec-sec-manifest',
      title: 'Audit & Remediasi Dependensi Rentan',
      category: 'security',
      impact: 'critical',
      effort: 'quick',
      badgeText: 'Kritis',
      description: 'Pemeriksaan versi package.json dari kerentanan OSV & CVE database global.',
      humanReason: 'Mencegah exploitasi package supply-chain dan menjamin kestabilan produksi.',
      suggestedPrompt: `Audit package.json pada ${repoFullName}, perbaiki paket yang rentan, dan tambahkan skrip audit berkala.`,
      quickActionLabel: 'Amankan Dependensi',
      status: 'idle',
    },
    {
      id: 'rec-arch-cellular',
      title: 'Penerapan Cellular Separation of Concerns',
      category: 'architecture',
      impact: 'high',
      effort: 'moderate',
      badgeText: 'Arsitektur',
      description: 'Pastikan komunikasi antar-fitur hanya melalui event dispatcher tanpa impor internal langsung.',
      humanReason: 'Menjaga kode mudah dirawat tanpa efek samping ketika satu modul diubah.',
      suggestedPrompt: `Refactor komunikasi antar modul pada ${repoFullName} agar 100% melewati dispatcher event bus.`,
      quickActionLabel: 'Terapkan Dispatcher',
      status: 'idle',
    },
    {
      id: 'rec-cicd-actions',
      title: 'Integrasi GitHub Actions CI/CD Build Gate',
      category: 'cicd',
      impact: 'high',
      effort: 'quick',
      badgeText: 'Automasi',
      description: 'Tambahkan gerbang verifikasi build otomatis setiap ada Pull Request atau Push baru.',
      humanReason: 'Menghindari regresi kode rusak masuk ke branch utama.',
      suggestedPrompt: `Generate file .github/workflows/ci.yml untuk otomatisasi verifikasi kode pada ${repoFullName}.`,
      quickActionLabel: 'Pasang GitHub Actions',
      status: 'idle',
    },
    {
      id: 'rec-test-coverage',
      title: 'Otomatisasi Unit Test & Edge Cases',
      category: 'testing',
      impact: 'medium',
      effort: 'moderate',
      badgeText: 'Pengujian',
      description: 'Tuliskan test suite untuk menguji happy path dan skenario error failure recovery.',
      humanReason: 'Memastikan fitur selalu berfungsi stabil walau terjadi error jaringan atau input tak terduga.',
      suggestedPrompt: `Buat unit test komprehensif untuk modul-modul logika utama pada repositori ${repoFullName}.`,
      quickActionLabel: 'Generate Test Suite',
      status: 'idle',
    },
    {
      id: 'rec-perf-cache',
      title: 'Cache Invalidation & Resilient Offline Mode',
      category: 'performance',
      impact: 'medium',
      effort: 'quick',
      badgeText: 'Performa',
      description: 'Simpan metadata repositori penting di penyimpanan lokal agar startup instan tanpa lag.',
      humanReason: 'Menghemat kuota API GitHub dan mempercepat waktu muat aplikasi.',
      suggestedPrompt: `Optimalkan strategi caching lokal dan sinkronisasi background untuk ${repoFullName}.`,
      quickActionLabel: 'Optimasi Cache',
      status: 'idle',
    },
  ];
}
